INSERT DATA 
{ 
GRAPH <http://www.pitt.edu/obc/ide/article-instances> { 
<http://www.pitt.edu/obc/IDE_0000000170>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000170>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001636> . 
<http://www.pitt.edu/obc/IDE_0000000170>	<http://purl.org/dc/elements/1.1/title>	"Computational Models Of Infectious Disease Threats"@en . 
<http://www.pitt.edu/obc/IDE_0000000170>	<http://purl.obolibrary.org/obo/IDE_0000000171>	"BURKE, DONALD S."@en . 
<http://www.pitt.edu/obc/IDE_0000000170>	<http://purl.obolibrary.org/obo/IDE_0000000172>	"RFA-GM-03-008"@en . 
<http://www.pitt.edu/obc/IDE_0000000170>	<http://purl.obolibrary.org/obo/IDE_0000000173>	"National Institute for General Medical Sciences"@en . 
<http://www.pitt.edu/obc/IDE_0000000170>	<http://purl.obolibrary.org/obo/IDE_0000000174>	"Johns Hopkins University"@en . 
<http://www.pitt.edu/obc/IDE_0000000170>	<http://purl.obolibrary.org/obo/IDE_0000000174>	"University of Pittsburgh"@en . 
<http://www.pitt.edu/obc/IDE_0000000170>	<http://purl.obolibrary.org/obo/IDE_0000000169>	"2004-05-01T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000170>	<http://purl.obolibrary.org/obo/IDE_0000000170>	"2009-06-30T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000171>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000171>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001636> . 
<http://www.pitt.edu/obc/IDE_0000000171>	<http://purl.org/dc/elements/1.1/title>	"Population Mobility Models Of Urban Disease Outbreak"@en . 
<http://www.pitt.edu/obc/IDE_0000000171>	<http://purl.obolibrary.org/obo/IDE_0000000171>	"EUBANK, STEPHEN G"@en . 
<http://www.pitt.edu/obc/IDE_0000000171>	<http://purl.obolibrary.org/obo/IDE_0000000172>	"RFA-GM-03-008"@en . 
<http://www.pitt.edu/obc/IDE_0000000171>	<http://purl.obolibrary.org/obo/IDE_0000000173>	"National Institute for General Medical Sciences"@en . 
<http://www.pitt.edu/obc/IDE_0000000171>	<http://purl.obolibrary.org/obo/IDE_0000000174>	"Los Alamos National Laboratory"@en . 
<http://www.pitt.edu/obc/IDE_0000000171>	<http://purl.obolibrary.org/obo/IDE_0000000174>	"Virginia Polytechnic Institute and State University"@en . 
<http://www.pitt.edu/obc/IDE_0000000171>	<http://purl.obolibrary.org/obo/IDE_0000000169>	"2004-05-01T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000171>	<http://purl.obolibrary.org/obo/IDE_0000000170>	"2016-08-31T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000174>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000174>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001636> . 
<http://www.pitt.edu/obc/IDE_0000000174>	<http://purl.org/dc/elements/1.1/title>	"Pilot Projects For Models If Infectious Diseases Agent Study"@en . 
<http://www.pitt.edu/obc/IDE_0000000174>	<http://purl.obolibrary.org/obo/IDE_0000000171>	"WAGENER, DIANE K"@en . 
<http://www.pitt.edu/obc/IDE_0000000174>	<http://purl.obolibrary.org/obo/IDE_0000000172>	"RFA-GM-03-008"@en . 
<http://www.pitt.edu/obc/IDE_0000000174>	<http://purl.obolibrary.org/obo/IDE_0000000173>	"National Institute for General Medical Sciences"@en . 
<http://www.pitt.edu/obc/IDE_0000000174>	<http://purl.obolibrary.org/obo/IDE_0000000174>	"RTI International"@en . 
<http://www.pitt.edu/obc/IDE_0000000174>	<http://purl.obolibrary.org/obo/IDE_0000000169>	"2004-05-01T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000174>	<http://purl.obolibrary.org/obo/IDE_0000000170>	"2010-05-31T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000176>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000176>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001636> . 
<http://www.pitt.edu/obc/IDE_0000000176>	<http://purl.org/dc/elements/1.1/title>	"Containing Bioterroist And Emerging Infectious Diseases"@en . 
<http://www.pitt.edu/obc/IDE_0000000176>	<http://purl.obolibrary.org/obo/IDE_0000000171>	"HALLORAN, M ELIZABETH"@en . 
<http://www.pitt.edu/obc/IDE_0000000176>	<http://purl.obolibrary.org/obo/IDE_0000000171>	"LONGINI, IRA M"@en . 
<http://www.pitt.edu/obc/IDE_0000000176>	<http://purl.obolibrary.org/obo/IDE_0000000172>	"RFA-GM-03-008"@en . 
<http://www.pitt.edu/obc/IDE_0000000176>	<http://purl.obolibrary.org/obo/IDE_0000000173>	"National Institute for General Medical Sciences"@en . 
<http://www.pitt.edu/obc/IDE_0000000176>	<http://purl.obolibrary.org/obo/IDE_0000000174>	"Emory University"@en . 
<http://www.pitt.edu/obc/IDE_0000000176>	<http://purl.obolibrary.org/obo/IDE_0000000174>	"Fred Hutchinson Cancer Research Center"@en . 
<http://www.pitt.edu/obc/IDE_0000000176>	<http://purl.obolibrary.org/obo/IDE_0000000169>	"2004-05-01T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000176>	<http://purl.obolibrary.org/obo/IDE_0000000170>	"2014-12-31T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000177>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000177>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001636> . 
<http://www.pitt.edu/obc/IDE_0000000177>	<http://purl.org/dc/elements/1.1/title>	"Hierarchical Models For The Spatio-Temporal Dynamics In…"@en . 
<http://www.pitt.edu/obc/IDE_0000000177>	<http://purl.obolibrary.org/obo/IDE_0000000171>	"SMITH, GARY"@en . 
<http://www.pitt.edu/obc/IDE_0000000177>	<http://purl.obolibrary.org/obo/IDE_0000000172>	"RFA-GM-05-011"@en . 
<http://www.pitt.edu/obc/IDE_0000000177>	<http://purl.obolibrary.org/obo/IDE_0000000173>	"National Institute for General Medical Sciences"@en . 
<http://www.pitt.edu/obc/IDE_0000000177>	<http://purl.obolibrary.org/obo/IDE_0000000174>	"University of Pennsylvania"@en . 
<http://www.pitt.edu/obc/IDE_0000000177>	<http://purl.obolibrary.org/obo/IDE_0000000169>	"2006-02-01T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000177>	<http://purl.obolibrary.org/obo/IDE_0000000170>	"2013-01-31T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000178>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000178>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001636> . 
<http://www.pitt.edu/obc/IDE_0000000178>	<http://purl.org/dc/elements/1.1/title>	"Methodological Approaches To Planning And Analysis Of N…"@en . 
<http://www.pitt.edu/obc/IDE_0000000178>	<http://purl.obolibrary.org/obo/IDE_0000000171>	"LIPSITCH, MARC"@en . 
<http://www.pitt.edu/obc/IDE_0000000178>	<http://purl.obolibrary.org/obo/IDE_0000000172>	"RFA-GM-05-011"@en . 
<http://www.pitt.edu/obc/IDE_0000000178>	<http://purl.obolibrary.org/obo/IDE_0000000173>	"National Institute for General Medical Sciences"@en . 
<http://www.pitt.edu/obc/IDE_0000000178>	<http://purl.obolibrary.org/obo/IDE_0000000174>	"Harvard T.H. Chan School of Public Health"@en . 
<http://www.pitt.edu/obc/IDE_0000000178>	<http://purl.obolibrary.org/obo/IDE_0000000169>	"2006-02-01T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000178>	<http://purl.obolibrary.org/obo/IDE_0000000170>	"2009-09-14T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000179>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000179>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001636> . 
<http://www.pitt.edu/obc/IDE_0000000179>	<http://purl.org/dc/elements/1.1/title>	"Computational Models Of Pathogen Evolution And Vaccinat…"@en . 
<http://www.pitt.edu/obc/IDE_0000000179>	<http://purl.obolibrary.org/obo/IDE_0000000171>	"BUSH, ROBIN M."@en . 
<http://www.pitt.edu/obc/IDE_0000000179>	<http://purl.obolibrary.org/obo/IDE_0000000172>	"RFA-GM-05-011"@en . 
<http://www.pitt.edu/obc/IDE_0000000179>	<http://purl.obolibrary.org/obo/IDE_0000000173>	"National Institute for General Medical Sciences"@en . 
<http://www.pitt.edu/obc/IDE_0000000179>	<http://purl.obolibrary.org/obo/IDE_0000000174>	"University of California, Irvine"@en . 
<http://www.pitt.edu/obc/IDE_0000000179>	<http://purl.obolibrary.org/obo/IDE_0000000169>	"2006-02-01T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000179>	<http://purl.obolibrary.org/obo/IDE_0000000170>	"2012-01-31T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000180>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000180>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001636> . 
<http://www.pitt.edu/obc/IDE_0000000180>	<http://purl.org/dc/elements/1.1/title>	"Modeling Health System Infectious Disease Data"@en . 
<http://www.pitt.edu/obc/IDE_0000000180>	<http://purl.obolibrary.org/obo/IDE_0000000171>	"HUANG, SUSAN S."@en . 
<http://www.pitt.edu/obc/IDE_0000000180>	<http://purl.obolibrary.org/obo/IDE_0000000171>	"PLATT, RICHARD"@en . 
<http://www.pitt.edu/obc/IDE_0000000180>	<http://purl.obolibrary.org/obo/IDE_0000000172>	"RFA-GM-05-011"@en . 
<http://www.pitt.edu/obc/IDE_0000000180>	<http://purl.obolibrary.org/obo/IDE_0000000173>	"National Institute for General Medical Sciences"@en . 
<http://www.pitt.edu/obc/IDE_0000000180>	<http://purl.obolibrary.org/obo/IDE_0000000174>	"University of California, Irvine"@en . 
<http://www.pitt.edu/obc/IDE_0000000180>	<http://purl.obolibrary.org/obo/IDE_0000000174>	"Harvard Pilgrim Health Care"@en . 
<http://www.pitt.edu/obc/IDE_0000000180>	<http://purl.obolibrary.org/obo/IDE_0000000169>	"2006-02-01T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000180>	<http://purl.obolibrary.org/obo/IDE_0000000170>	"2012-01-31T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000181>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000181>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001636> . 
<http://www.pitt.edu/obc/IDE_0000000181>	<http://purl.org/dc/elements/1.1/title>	"Modeling Of Infectious Disease Agent Study Information Technology"@en . 
<http://www.pitt.edu/obc/IDE_0000000181>	<http://purl.obolibrary.org/obo/IDE_0000000171>	"WAGENER, DIANE K"@en . 
<http://www.pitt.edu/obc/IDE_0000000181>	<http://purl.obolibrary.org/obo/IDE_0000000171>	"COOLEY, PHILIP C"@en . 
<http://www.pitt.edu/obc/IDE_0000000181>	<http://purl.obolibrary.org/obo/IDE_0000000172>	"RFA-GM-09-002"@en . 
<http://www.pitt.edu/obc/IDE_0000000181>	<http://purl.obolibrary.org/obo/IDE_0000000173>	"National Institute for General Medical Sciences"@en . 
<http://www.pitt.edu/obc/IDE_0000000181>	<http://purl.obolibrary.org/obo/IDE_0000000174>	"RTI International"@en . 
<http://www.pitt.edu/obc/IDE_0000000181>	<http://purl.obolibrary.org/obo/IDE_0000000169>	"2009-06-01T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000181>	<http://purl.obolibrary.org/obo/IDE_0000000170>	"2014-09-30T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000182>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000182>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001636> . 
<http://www.pitt.edu/obc/IDE_0000000182>	<http://purl.org/dc/elements/1.1/title>	"Impacts Of Individual And Social Behavior On Influenza Dynamics And Control"@en . 
<http://www.pitt.edu/obc/IDE_0000000182>	<http://purl.obolibrary.org/obo/IDE_0000000171>	"GALVANI, ALISON P"@en . 
<http://www.pitt.edu/obc/IDE_0000000182>	<http://purl.obolibrary.org/obo/IDE_0000000172>	"RFA-GM-09-001"@en . 
<http://www.pitt.edu/obc/IDE_0000000182>	<http://purl.obolibrary.org/obo/IDE_0000000173>	"National Institute for General Medical Sciences"@en . 
<http://www.pitt.edu/obc/IDE_0000000182>	<http://purl.obolibrary.org/obo/IDE_0000000174>	"Yale University"@en . 
<http://www.pitt.edu/obc/IDE_0000000182>	<http://purl.obolibrary.org/obo/IDE_0000000169>	"2009-06-01T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000182>	<http://purl.obolibrary.org/obo/IDE_0000000170>	"2019-04-30T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000183>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000183>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001636> . 
<http://www.pitt.edu/obc/IDE_0000000183>	<http://purl.org/dc/elements/1.1/title>	"Modeling Contact Investigation And Rapid Response"@en . 
<http://www.pitt.edu/obc/IDE_0000000183>	<http://purl.obolibrary.org/obo/IDE_0000000171>	"PORCO, TRAVIS CHRISTIAN"@en . 
<http://www.pitt.edu/obc/IDE_0000000183>	<http://purl.obolibrary.org/obo/IDE_0000000172>	"RFA-GM-11-002"@en . 
<http://www.pitt.edu/obc/IDE_0000000183>	<http://purl.obolibrary.org/obo/IDE_0000000173>	"National Institute for General Medical Sciences"@en . 
<http://www.pitt.edu/obc/IDE_0000000183>	<http://purl.obolibrary.org/obo/IDE_0000000174>	"University of California, San Francisco"@en . 
<http://www.pitt.edu/obc/IDE_0000000183>	<http://purl.obolibrary.org/obo/IDE_0000000169>	"2011-08-01T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000183>	<http://purl.obolibrary.org/obo/IDE_0000000170>	"2016-06-30T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000184>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000184>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001636> . 
<http://www.pitt.edu/obc/IDE_0000000184>	<http://purl.org/dc/elements/1.1/title>	"Modeling MRSA In The Community"@en . 
<http://www.pitt.edu/obc/IDE_0000000184>	<http://purl.obolibrary.org/obo/IDE_0000000171>	"LAUDERDALE, DIANE SPERLING"@en . 
<http://www.pitt.edu/obc/IDE_0000000184>	<http://purl.obolibrary.org/obo/IDE_0000000172>	"RFA-GM-09-001"@en . 
<http://www.pitt.edu/obc/IDE_0000000184>	<http://purl.obolibrary.org/obo/IDE_0000000173>	"National Institute for General Medical Sciences"@en . 
<http://www.pitt.edu/obc/IDE_0000000184>	<http://purl.obolibrary.org/obo/IDE_0000000174>	"University of Chicago"@en . 
<http://www.pitt.edu/obc/IDE_0000000184>	<http://purl.obolibrary.org/obo/IDE_0000000169>	"2009-05-08T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000184>	<http://purl.obolibrary.org/obo/IDE_0000000170>	"2015-04-30T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000185>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000185>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001636> . 
<http://www.pitt.edu/obc/IDE_0000000185>	<http://purl.org/dc/elements/1.1/title>	"Computational Models Of Infectious Disease Threats 2"@en . 
<http://www.pitt.edu/obc/IDE_0000000185>	<http://purl.obolibrary.org/obo/IDE_0000000171>	"BURKE, DONALD S."@en . 
<http://www.pitt.edu/obc/IDE_0000000185>	<http://purl.obolibrary.org/obo/IDE_0000000172>	"RFA-GM-09-003"@en . 
<http://www.pitt.edu/obc/IDE_0000000185>	<http://purl.obolibrary.org/obo/IDE_0000000173>	"National Institute for General Medical Sciences"@en . 
<http://www.pitt.edu/obc/IDE_0000000185>	<http://purl.obolibrary.org/obo/IDE_0000000174>	"University of Pittsburgh"@en . 
<http://www.pitt.edu/obc/IDE_0000000185>	<http://purl.obolibrary.org/obo/IDE_0000000169>	"2009-07-24T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000185>	<http://purl.obolibrary.org/obo/IDE_0000000170>	"2019-06-30T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000186>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000186>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001636> . 
<http://www.pitt.edu/obc/IDE_0000000186>	<http://purl.org/dc/elements/1.1/title>	"MIDAS Center For Communicable Disease Dynamics"@en . 
<http://www.pitt.edu/obc/IDE_0000000186>	<http://purl.obolibrary.org/obo/IDE_0000000171>	"LIPSITCH, MARC"@en . 
<http://www.pitt.edu/obc/IDE_0000000186>	<http://purl.obolibrary.org/obo/IDE_0000000172>	"RFA-GM-09-003"@en . 
<http://www.pitt.edu/obc/IDE_0000000186>	<http://purl.obolibrary.org/obo/IDE_0000000173>	"National Institute for General Medical Sciences"@en . 
<http://www.pitt.edu/obc/IDE_0000000186>	<http://purl.obolibrary.org/obo/IDE_0000000174>	"Harvard T.H. Chan School of Public Health"@en . 
<http://www.pitt.edu/obc/IDE_0000000186>	<http://purl.obolibrary.org/obo/IDE_0000000169>	"2009-09-15T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000186>	<http://purl.obolibrary.org/obo/IDE_0000000170>	"2019-08-31T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000187>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000187>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001636> . 
<http://www.pitt.edu/obc/IDE_0000000187>	<http://purl.org/dc/elements/1.1/title>	"Quantifying Model Uncertainty For Forecasting The Spread Of Infectious Diseases"@en . 
<http://www.pitt.edu/obc/IDE_0000000187>	<http://purl.obolibrary.org/obo/IDE_0000000171>	"DEL VALLE, SARA"@en . 
<http://www.pitt.edu/obc/IDE_0000000187>	<http://purl.obolibrary.org/obo/IDE_0000000172>	"RFA-GM-11-002"@en . 
<http://www.pitt.edu/obc/IDE_0000000187>	<http://purl.obolibrary.org/obo/IDE_0000000173>	"National Institute for General Medical Sciences"@en . 
<http://www.pitt.edu/obc/IDE_0000000187>	<http://purl.obolibrary.org/obo/IDE_0000000174>	"Los Alamos National Security, Los Alamos National Laboratory"@en . 
<http://www.pitt.edu/obc/IDE_0000000187>	<http://purl.obolibrary.org/obo/IDE_0000000169>	"2011-06-01T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000187>	<http://purl.obolibrary.org/obo/IDE_0000000170>	"2016-04-30T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000188>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000188>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001636> . 
<http://www.pitt.edu/obc/IDE_0000000188>	<http://purl.org/dc/elements/1.1/title>	"Predicting Vector-Borne Virus Transmission Dynamics And Emergence Potential"@en . 
<http://www.pitt.edu/obc/IDE_0000000188>	<http://purl.obolibrary.org/obo/IDE_0000000171>	"MORES, CHRISTOPHER"@en . 
<http://www.pitt.edu/obc/IDE_0000000188>	<http://purl.obolibrary.org/obo/IDE_0000000172>	"RFA-GM-11-002"@en . 
<http://www.pitt.edu/obc/IDE_0000000188>	<http://purl.obolibrary.org/obo/IDE_0000000173>	"National Institute for General Medical Sciences"@en . 
<http://www.pitt.edu/obc/IDE_0000000188>	<http://purl.obolibrary.org/obo/IDE_0000000174>	"Louisiana State University, Southern University and A&M College"@en . 
<http://www.pitt.edu/obc/IDE_0000000188>	<http://purl.obolibrary.org/obo/IDE_0000000169>	"2011-06-15T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000188>	<http://purl.obolibrary.org/obo/IDE_0000000170>	"2016-04-30T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000189>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000189>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001636> . 
<http://www.pitt.edu/obc/IDE_0000000189>	<http://purl.org/dc/elements/1.1/title>	"MIDAS Informatics Services Group (Isg)"@en . 
<http://www.pitt.edu/obc/IDE_0000000189>	<http://purl.obolibrary.org/obo/IDE_0000000171>	"WAGNER, MICHAEL MATTHEW"@en . 
<http://www.pitt.edu/obc/IDE_0000000189>	<http://purl.obolibrary.org/obo/IDE_0000000172>	"RFA-GM-14-008"@en . 
<http://www.pitt.edu/obc/IDE_0000000189>	<http://purl.obolibrary.org/obo/IDE_0000000173>	"National Institute for General Medical Sciences"@en . 
<http://www.pitt.edu/obc/IDE_0000000189>	<http://purl.obolibrary.org/obo/IDE_0000000174>	"University of Pittsburgh"@en . 
<http://www.pitt.edu/obc/IDE_0000000189>	<http://purl.obolibrary.org/obo/IDE_0000000169>	"2014-08-05T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000189>	<http://purl.obolibrary.org/obo/IDE_0000000170>	"2019-04-30T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000190>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000190>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001636> . 
<http://www.pitt.edu/obc/IDE_0000000190>	<http://purl.org/dc/elements/1.1/title>	"Modeling The Effects Of The Environment On Enteric Pathogen Dynamics"@en . 
<http://www.pitt.edu/obc/IDE_0000000190>	<http://purl.obolibrary.org/obo/IDE_0000000171>	"EISENBERG, JOSEPH N. S."@en . 
<http://www.pitt.edu/obc/IDE_0000000190>	<http://purl.obolibrary.org/obo/IDE_0000000172>	"RFA-GM-14-007"@en . 
<http://www.pitt.edu/obc/IDE_0000000190>	<http://purl.obolibrary.org/obo/IDE_0000000173>	"National Institute for General Medical Sciences"@en . 
<http://www.pitt.edu/obc/IDE_0000000190>	<http://purl.obolibrary.org/obo/IDE_0000000174>	"University of Michigan - Ann Arbor"@en . 
<http://www.pitt.edu/obc/IDE_0000000190>	<http://purl.obolibrary.org/obo/IDE_0000000169>	"2014-09-01T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000190>	<http://purl.obolibrary.org/obo/IDE_0000000170>	"2019-06-30T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000191>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000191>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001636> . 
<http://www.pitt.edu/obc/IDE_0000000191>	<http://purl.org/dc/elements/1.1/title>	"Models For Synthesising Molecular, Clinical And Epidemiological Data, And Transla"@en . 
<http://www.pitt.edu/obc/IDE_0000000191>	<http://purl.obolibrary.org/obo/IDE_0000000171>	"FERGUSON, NEIL MORRIS"@en . 
<http://www.pitt.edu/obc/IDE_0000000191>	<http://purl.obolibrary.org/obo/IDE_0000000172>	"RFA-GM-14-007"@en . 
<http://www.pitt.edu/obc/IDE_0000000191>	<http://purl.obolibrary.org/obo/IDE_0000000173>	"National Institute for General Medical Sciences"@en . 
<http://www.pitt.edu/obc/IDE_0000000191>	<http://purl.obolibrary.org/obo/IDE_0000000174>	"Imperial College London"@en . 
<http://www.pitt.edu/obc/IDE_0000000191>	<http://purl.obolibrary.org/obo/IDE_0000000169>	"2014-09-15T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000191>	<http://purl.obolibrary.org/obo/IDE_0000000170>	"2019-05-31T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000192>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000192>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001636> . 
<http://www.pitt.edu/obc/IDE_0000000192>	<http://purl.org/dc/elements/1.1/title>	"Forecasting Tipping Points In Emerging And Re-Emerging Infectious Diseases"@en . 
<http://www.pitt.edu/obc/IDE_0000000192>	<http://purl.obolibrary.org/obo/IDE_0000000171>	"DRAKE, JOHN M"@en . 
<http://www.pitt.edu/obc/IDE_0000000192>	<http://purl.obolibrary.org/obo/IDE_0000000172>	"RFA-GM-14-007"@en . 
<http://www.pitt.edu/obc/IDE_0000000192>	<http://purl.obolibrary.org/obo/IDE_0000000173>	"National Institute for General Medical Sciences"@en . 
<http://www.pitt.edu/obc/IDE_0000000192>	<http://purl.obolibrary.org/obo/IDE_0000000174>	"University of Georgia"@en . 
<http://www.pitt.edu/obc/IDE_0000000192>	<http://purl.obolibrary.org/obo/IDE_0000000169>	"2014-09-12T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000192>	<http://purl.obolibrary.org/obo/IDE_0000000170>	"2019-05-31T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000193>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000193>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001636> . 
<http://www.pitt.edu/obc/IDE_0000000193>	<http://purl.org/dc/elements/1.1/title>	"Development And Dissemination Of Operational Real-Time Respiratory Virus Forecast"@en . 
<http://www.pitt.edu/obc/IDE_0000000193>	<http://purl.obolibrary.org/obo/IDE_0000000171>	"SHAMAN, JEFFREY L"@en . 
<http://www.pitt.edu/obc/IDE_0000000193>	<http://purl.obolibrary.org/obo/IDE_0000000172>	"RFA-GM-14-007"@en . 
<http://www.pitt.edu/obc/IDE_0000000193>	<http://purl.obolibrary.org/obo/IDE_0000000173>	"National Institute for General Medical Sciences"@en . 
<http://www.pitt.edu/obc/IDE_0000000193>	<http://purl.obolibrary.org/obo/IDE_0000000174>	"Columbia University"@en . 
<http://www.pitt.edu/obc/IDE_0000000193>	<http://purl.obolibrary.org/obo/IDE_0000000169>	"2014-09-01T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000193>	<http://purl.obolibrary.org/obo/IDE_0000000170>	"2019-06-30T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000194>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000194>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001636> . 
<http://www.pitt.edu/obc/IDE_0000000194>	<http://purl.org/dc/elements/1.1/title>	"Modeling Epidemic Infectious Diseases Using Sequence Analysis"@en . 
<http://www.pitt.edu/obc/IDE_0000000194>	<http://purl.obolibrary.org/obo/IDE_0000000171>	"POND, SERGEI L KOSAKOVSKY"@en . 
<http://www.pitt.edu/obc/IDE_0000000194>	<http://purl.obolibrary.org/obo/IDE_0000000172>	"RFA-GM-14-007"@en . 
<http://www.pitt.edu/obc/IDE_0000000194>	<http://purl.obolibrary.org/obo/IDE_0000000173>	"National Institute for General Medical Sciences"@en . 
<http://www.pitt.edu/obc/IDE_0000000194>	<http://purl.obolibrary.org/obo/IDE_0000000174>	"University of California, San Diego"@en . 
<http://www.pitt.edu/obc/IDE_0000000194>	<http://purl.obolibrary.org/obo/IDE_0000000169>	"2014-09-05T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000194>	<http://purl.obolibrary.org/obo/IDE_0000000170>	"2019-05-31T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000195>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000195>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001636> . 
<http://www.pitt.edu/obc/IDE_0000000195>	<http://purl.org/dc/elements/1.1/title>	"Dynamics And Evolution Of Influenza Strain Variation"@en . 
<http://www.pitt.edu/obc/IDE_0000000195>	<http://purl.obolibrary.org/obo/IDE_0000000171>	"HALLORAN, M ELIZABETH"@en . 
<http://www.pitt.edu/obc/IDE_0000000195>	<http://purl.obolibrary.org/obo/IDE_0000000172>	"RFA-GM-14-009"@en . 
<http://www.pitt.edu/obc/IDE_0000000195>	<http://purl.obolibrary.org/obo/IDE_0000000173>	"National Institute for General Medical Sciences"@en . 
<http://www.pitt.edu/obc/IDE_0000000195>	<http://purl.obolibrary.org/obo/IDE_0000000174>	"Fred Hutchinson Cancer Research Center"@en . 
<http://www.pitt.edu/obc/IDE_0000000195>	<http://purl.obolibrary.org/obo/IDE_0000000169>	"2014-09-12T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
<http://www.pitt.edu/obc/IDE_0000000195>	<http://purl.obolibrary.org/obo/IDE_0000000170>	"2019-06-30T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> 
}