INSERT DATA 
{ 
GRAPH <http://www.pitt.edu/obc/ide/article-instances> { 
<http://www.pitt.edu/obc/IDE_0000000169>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000169>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001629> . 
<http://www.pitt.edu/obc/IDE_0000000169>	<http://www.w3.org/2000/01/rdf-schema#label>	"U01GM070708"@en . 
<http://www.pitt.edu/obc/IDE_0000000169>	<http://purl.obolibrary.org/obo/IAO_0000219>	<http://www.pitt.edu/obc/IDE_0000000170> . 
<http://www.pitt.edu/obc/IDE_0000000172>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000172>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001629> . 
<http://www.pitt.edu/obc/IDE_0000000172>	<http://www.w3.org/2000/01/rdf-schema#label>	"U01GM070694"@en . 
<http://www.pitt.edu/obc/IDE_0000000172>	<http://purl.obolibrary.org/obo/IAO_0000219>	<http://www.pitt.edu/obc/IDE_0000000171> . 
<http://www.pitt.edu/obc/IDE_0000000175>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000175>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001629> . 
<http://www.pitt.edu/obc/IDE_0000000175>	<http://www.w3.org/2000/01/rdf-schema#label>	"U01GM070698"@en . 
<http://www.pitt.edu/obc/IDE_0000000175>	<http://purl.obolibrary.org/obo/IAO_0000219>	<http://www.pitt.edu/obc/IDE_0000000174> . 
<http://www.pitt.edu/obc/IDE_0000000196>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000196>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001629> . 
<http://www.pitt.edu/obc/IDE_0000000196>	<http://www.w3.org/2000/01/rdf-schema#label>	"U01GM070749"@en . 
<http://www.pitt.edu/obc/IDE_0000000196>	<http://purl.obolibrary.org/obo/IAO_0000219>	<http://www.pitt.edu/obc/IDE_0000000176> . 
<http://www.pitt.edu/obc/IDE_0000000197>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000197>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001629> . 
<http://www.pitt.edu/obc/IDE_0000000197>	<http://www.w3.org/2000/01/rdf-schema#label>	"U01GM076426"@en . 
<http://www.pitt.edu/obc/IDE_0000000197>	<http://purl.obolibrary.org/obo/IAO_0000219>	<http://www.pitt.edu/obc/IDE_0000000177> . 
<http://www.pitt.edu/obc/IDE_0000000198>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000198>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001629> . 
<http://www.pitt.edu/obc/IDE_0000000198>	<http://www.w3.org/2000/01/rdf-schema#label>	"U01GM076497"@en . 
<http://www.pitt.edu/obc/IDE_0000000198>	<http://purl.obolibrary.org/obo/IAO_0000219>	<http://www.pitt.edu/obc/IDE_0000000178> . 
<http://www.pitt.edu/obc/IDE_0000000199>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000199>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001629> . 
<http://www.pitt.edu/obc/IDE_0000000199>	<http://www.w3.org/2000/01/rdf-schema#label>	"U01GM076499"@en . 
<http://www.pitt.edu/obc/IDE_0000000199>	<http://purl.obolibrary.org/obo/IAO_0000219>	<http://www.pitt.edu/obc/IDE_0000000179> . 
<http://www.pitt.edu/obc/IDE_0000000200>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000200>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001629> . 
<http://www.pitt.edu/obc/IDE_0000000200>	<http://www.w3.org/2000/01/rdf-schema#label>	"U01GM076672"@en . 
<http://www.pitt.edu/obc/IDE_0000000200>	<http://purl.obolibrary.org/obo/IAO_0000219>	<http://www.pitt.edu/obc/IDE_0000000180> . 
<http://www.pitt.edu/obc/IDE_0000000201>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000201>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001629> . 
<http://www.pitt.edu/obc/IDE_0000000201>	<http://www.w3.org/2000/01/rdf-schema#label>	"U24GM087704"@en . 
<http://www.pitt.edu/obc/IDE_0000000201>	<http://purl.obolibrary.org/obo/IAO_0000219>	<http://www.pitt.edu/obc/IDE_0000000181> . 
<http://www.pitt.edu/obc/IDE_0000000202>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000202>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001629> . 
<http://www.pitt.edu/obc/IDE_0000000202>	<http://www.w3.org/2000/01/rdf-schema#label>	"U01GM087719"@en . 
<http://www.pitt.edu/obc/IDE_0000000202>	<http://purl.obolibrary.org/obo/IAO_0000219>	<http://www.pitt.edu/obc/IDE_0000000182> . 
<http://www.pitt.edu/obc/IDE_0000000203>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000203>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001629> . 
<http://www.pitt.edu/obc/IDE_0000000203>	<http://www.w3.org/2000/01/rdf-schema#label>	"U01GM087728"@en . 
<http://www.pitt.edu/obc/IDE_0000000203>	<http://purl.obolibrary.org/obo/IAO_0000219>	<http://www.pitt.edu/obc/IDE_0000000183> . 
<http://www.pitt.edu/obc/IDE_0000000204>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000204>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001629> . 
<http://www.pitt.edu/obc/IDE_0000000204>	<http://www.w3.org/2000/01/rdf-schema#label>	"U01GM087729"@en . 
<http://www.pitt.edu/obc/IDE_0000000204>	<http://purl.obolibrary.org/obo/IAO_0000219>	<http://www.pitt.edu/obc/IDE_0000000184> . 
<http://www.pitt.edu/obc/IDE_0000000205>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000205>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001629> . 
<http://www.pitt.edu/obc/IDE_0000000205>	<http://www.w3.org/2000/01/rdf-schema#label>	"U54GM088491"@en . 
<http://www.pitt.edu/obc/IDE_0000000205>	<http://purl.obolibrary.org/obo/IAO_0000219>	<http://www.pitt.edu/obc/IDE_0000000185> . 
<http://www.pitt.edu/obc/IDE_0000000206>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000206>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001629> . 
<http://www.pitt.edu/obc/IDE_0000000206>	<http://www.w3.org/2000/01/rdf-schema#label>	"U54GM088558"@en . 
<http://www.pitt.edu/obc/IDE_0000000206>	<http://purl.obolibrary.org/obo/IAO_0000219>	<http://www.pitt.edu/obc/IDE_0000000186> . 
<http://www.pitt.edu/obc/IDE_0000000207>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000207>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001629> . 
<http://www.pitt.edu/obc/IDE_0000000207>	<http://www.w3.org/2000/01/rdf-schema#label>	"U01GM097658"@en . 
<http://www.pitt.edu/obc/IDE_0000000207>	<http://purl.obolibrary.org/obo/IAO_0000219>	<http://www.pitt.edu/obc/IDE_0000000187> . 
<http://www.pitt.edu/obc/IDE_0000000208>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000208>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001629> . 
<http://www.pitt.edu/obc/IDE_0000000208>	<http://www.w3.org/2000/01/rdf-schema#label>	"U01GM097661"@en . 
<http://www.pitt.edu/obc/IDE_0000000208>	<http://purl.obolibrary.org/obo/IAO_0000219>	<http://www.pitt.edu/obc/IDE_0000000188> . 
<http://www.pitt.edu/obc/IDE_0000000209>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000209>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001629> . 
<http://www.pitt.edu/obc/IDE_0000000209>	<http://www.w3.org/2000/01/rdf-schema#label>	"U24GM110707"@en . 
<http://www.pitt.edu/obc/IDE_0000000209>	<http://purl.obolibrary.org/obo/IAO_0000219>	<http://www.pitt.edu/obc/IDE_0000000189> . 
<http://www.pitt.edu/obc/IDE_0000000210>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000210>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001629> . 
<http://www.pitt.edu/obc/IDE_0000000210>	<http://www.w3.org/2000/01/rdf-schema#label>	"U01GM110712"@en . 
<http://www.pitt.edu/obc/IDE_0000000210>	<http://purl.obolibrary.org/obo/IAO_0000219>	<http://www.pitt.edu/obc/IDE_0000000190> . 
<http://www.pitt.edu/obc/IDE_0000000211>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000211>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001629> . 
<http://www.pitt.edu/obc/IDE_0000000211>	<http://www.w3.org/2000/01/rdf-schema#label>	"U01GM110721"@en . 
<http://www.pitt.edu/obc/IDE_0000000211>	<http://purl.obolibrary.org/obo/IAO_0000219>	<http://www.pitt.edu/obc/IDE_0000000191> . 
<http://www.pitt.edu/obc/IDE_0000000212>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000212>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001629> . 
<http://www.pitt.edu/obc/IDE_0000000212>	<http://www.w3.org/2000/01/rdf-schema#label>	"U01GM110744"@en . 
<http://www.pitt.edu/obc/IDE_0000000212>	<http://purl.obolibrary.org/obo/IAO_0000219>	<http://www.pitt.edu/obc/IDE_0000000192> . 
<http://www.pitt.edu/obc/IDE_0000000213>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000213>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001629> . 
<http://www.pitt.edu/obc/IDE_0000000213>	<http://www.w3.org/2000/01/rdf-schema#label>	"U01GM110748"@en . 
<http://www.pitt.edu/obc/IDE_0000000213>	<http://purl.obolibrary.org/obo/IAO_0000219>	<http://www.pitt.edu/obc/IDE_0000000193> . 
<http://www.pitt.edu/obc/IDE_0000000214>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000214>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001629> . 
<http://www.pitt.edu/obc/IDE_0000000214>	<http://www.w3.org/2000/01/rdf-schema#label>	"U01GM110749"@en . 
<http://www.pitt.edu/obc/IDE_0000000214>	<http://purl.obolibrary.org/obo/IAO_0000219>	<http://www.pitt.edu/obc/IDE_0000000194> . 
<http://www.pitt.edu/obc/IDE_0000000215>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2002/07/owl#NamedIndividual> . 
<http://www.pitt.edu/obc/IDE_0000000215>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://purl.obolibrary.org/obo/OBI_0001629> . 
<http://www.pitt.edu/obc/IDE_0000000215>	<http://www.w3.org/2000/01/rdf-schema#label>	"U54GM111274"@en . 
<http://www.pitt.edu/obc/IDE_0000000215>	<http://purl.obolibrary.org/obo/IAO_0000219>	<http://www.pitt.edu/obc/IDE_0000000195> 
}}